# Workflow to build and deploy to your GitHub Pages repo.
# @see https://docs.astro.build/en/guides/deploy/

env:
  # When changing email remember to add API_TOKEN_GITHUB in repo Settings > Secrets as well!
  githubEmail: vesa.piittinen@gmail.com
  githubUserOrOrg: vr-digital-crew-aikajana
  deployToRepo: menopaluu

name: Github Pages Astro CI

on:
  # Triggers the workflow on push and pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Copy over .npmrc file
        shell: bash
        run: |
          cat > ./.npmrc << EOF
          @vr-core:registry=https://vrartifactory.eficode.com/api/npm/channel-core-npm/
          //vrartifactory.eficode.com/api/npm/channel-core-npm/:_password=\${ARTIFACTORY_PASSWORD}
          //vrartifactory.eficode.com/api/npm/channel-core-npm/:username=\${ARTIFACTORY_USERNAME}
          //vrartifactory.eficode.com/api/npm/channel-core-npm/:email=\${ARTIFACTORY_EMAIL}
          //vrartifactory.eficode.com/api/npm/channel-core-npm/:always-auth=true
          //vrartifactory.eficode.com/api/npm/channel-core-npm/:_authToken=\${ARTIFACTORY_AUTH_TOKEN}
          EOF

      # Install dependencies with npm
      - name: Install dependencies
        run: npm ci
        env:
          ARTIFACTORY_AUTH_TOKEN: ${{ secrets.ARTIFACTORY_AUTH_TOKEN }}
          ARTIFACTORY_EMAIL: ${{ secrets.ARTIFACTORY_EMAIL }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}

      # Build the project and add .nojekyll file to supress default behaviour
      - name: Build
        run: |
          npm run build
          touch ./dist/.nojekyll

      - name: Cleanup .npmrc file
        if: always()
        shell: bash
        run: rm ./.npmrc

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: dist
          target-folder: docs
