# Workflow to build and deploy to your GitHub Pages repo.
# @see https://docs.astro.build/en/guides/deploy/

env:
  # When changing email remember to add API_TOKEN_GITHUB in repo Settings > Secrets as well!
  githubEmail: vesa.piittinen@gmail.com
  deployToRepo: vr-digital-crew-aikajana.github.io/menopaluu

name: Github Pages Astro CI

on:
  # Triggers the workflow on push and pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Copy over .npmrc file
        shell: bash
        run: |
          cat > ./.npmrc << EOF
          //vrartifactory.eficode.com/api/npm/channel-core-npm/:_authToken=\${ARTIFACTORY_AUTH_TOKEN}
          //vrartifactory.eficode.com/api/npm/channel-core-npm/:always-auth=true
          //vrartifactory.eficode.com/api/npm/channel-core-npm/:email=\${ARTIFACTORY_EMAIL}
          @vr-core:registry=https://vrartifactory.eficode.com/api/npm/channel-core-npm/
          EOF

      # Install dependencies with npm
      - name: Install dependencies
        run: npm ci

      # Build the project and add .nojekyll file to supress default behaviour
      - name: Build
        run: |
          npm run build
          touch ./dist/.nojekyll

      # Push to your pages repo
      - name: Push to pages repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'dist'
          destination-github-username: ${{ github.actor }}
          destination-repository-name: ${{ env.deployToRepo }}
          user-email: ${{ env.githubEmail }}
          commit-message: Deploy ORIGIN_COMMIT
          target-branch: gh-pages